'use client'

import { useState } from 'react'
import type { Quest } from '@/lib/types'
import { api } from '@/lib/api'
import { Trophy, Check, Loader2, Target } from 'lucide-react'

export function QuestBoard({ quests, onRefresh, onTrophiesChanged }: { quests: Quest[] | null; onRefresh: () => Promise<void>; onTrophiesChanged: () => Promise<void> }) {
  const [claiming, setClaiming] = useState<string | null>(null)
  const [message, setMessage] = useState<string | null>(null)
  const claim = async (id: string) => { setClaiming(id); setMessage(null); try { const result = await api.claimQuest(id); setMessage(`+${result.trophiesAwarded.toLocaleString()} trophies added`); await Promise.all([onRefresh(), onTrophiesChanged()]) } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Unable to claim quest') } finally { setClaiming(null) } }
  if (!quests) return <PanelMessage label="Loading quests…" />
  const daily = quests.filter((quest) => quest.period === 'daily')
  const weekly = quests.filter((quest) => quest.period === 'weekly')
  return <div className="space-y-7"><div className="flex items-end justify-between"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-cyan-300">Missions</p><h2 className="mt-1 text-2xl font-black text-white">Quest board</h2></div>{message && <p className="text-right text-xs text-emerald-300">{message}</p>}</div><QuestGroup title="Daily quests" quests={daily} claiming={claiming} onClaim={claim} /><QuestGroup title="Weekly quests" quests={weekly} claiming={claiming} onClaim={claim} /></div>
}

function QuestGroup({ title, quests, claiming, onClaim }: { title: string; quests: Quest[]; claiming: string | null; onClaim: (id: string) => void }) { return <section><div className="mb-3 flex items-center gap-2"><Target className="size-4 text-cyan-300" /><h3 className="font-bold text-white">{title}</h3><span className="text-xs text-zinc-600">{quests.length} available</span></div>{quests.length === 0 ? <PanelMessage label="No quests available right now." /> : <div className="grid gap-3 md:grid-cols-2">{quests.map((quest) => <article key={quest.id} className="rounded-2xl border border-white/10 bg-white/[0.035] p-4 transition hover:border-white/20"><div className="flex items-start justify-between gap-4"><div><h4 className="font-bold text-white">{quest.title}</h4><p className="mt-1 text-xs text-zinc-500">{quest.description ?? 'Complete this mission to earn trophies.'}</p></div><span className="flex shrink-0 items-center gap-1 rounded-full bg-yellow-300/10 px-2 py-1 font-mono text-xs font-bold text-yellow-200"><Trophy className="size-3" /> +{quest.reward.toLocaleString()}</span></div><div className="mt-5"><div className="mb-2 flex justify-between font-mono text-xs text-zinc-500"><span>{quest.completed ? 'Completed' : 'In progress'}</span><span>{quest.progress} / {quest.target}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-300 transition-all" style={{ width: `${Math.min(100, quest.target ? quest.progress / quest.target * 100 : 0)}%` }} /></div></div>{quest.completed && <div className="mt-4 flex items-center justify-between">{quest.claimed ? <span className="flex items-center gap-1.5 text-xs font-bold text-emerald-300"><Check className="size-4" /> Claimed</span> : <button onClick={() => onClaim(quest.id)} disabled={claiming === quest.id} className="rounded-lg bg-cyan-300 px-4 py-2 text-xs font-black text-zinc-950 hover:bg-cyan-200 disabled:opacity-50">{claiming === quest.id ? <Loader2 className="size-4 animate-spin" /> : 'CLAIM'}</button>}</div>}</article>)}</div>}</section> }
function PanelMessage({ label }: { label: string }) { return <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.02] p-8 text-center text-sm text-zinc-500">{label}</div> }
