const ADMIN_PORTAL = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>DASHCUP Admin · Reward Inventory</title>
<style nonce="__CSP_NONCE__">
:root{color-scheme:dark;font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;background:#0c1127;color:#f6f7ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 20% 0,#1a3565 0,transparent 48%),#0c1127;min-height:100vh}.wrap{width:min(1120px,100% - 32px);margin:0 auto;padding:40px 0 64px}.brand{color:#70e8f8;font-size:12px;font-weight:900;letter-spacing:.22em}.head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:28px}h1{font-size:clamp(26px,4vw,40px);margin:8px 0 0;letter-spacing:-.04em}.card,.category{background:#151d3a;border:1px solid #313d69;border-radius:20px;padding:22px;box-shadow:0 8px 0 #080c1b}.login{max-width:440px;margin:12vh auto}.field{display:grid;gap:8px;margin:16px 0;font-size:13px;color:#b9c5ed;font-weight:700}input,select{min-width:0;background:#0c1228;color:#fff;border:1px solid #3a4774;border-radius:10px;padding:12px;font:inherit}button{border:0;border-radius:10px;padding:12px 16px;background:#70e8f8;color:#10182f;font-weight:900;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}.secondary{background:#263354;color:#e4eaff}.danger{background:#482e3d;color:#ffb9d8}.hidden{display:none!important}.muted{color:#a5b0d0;font-size:13px}.error{color:#ffb3c7;min-height:20px}.good{color:#a9ffd2}.topline{display:flex;justify-content:space-between;align-items:center;gap:10px}.categories{display:grid;gap:22px}.category h2{margin:0 0 5px}.counts{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.pill{border:1px solid #394872;border-radius:999px;padding:6px 10px;color:#cfdaff;font-size:12px}.slots{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}.slot{padding:12px;border:1px solid #303e68;border-radius:14px;background:#0e152d}.slot-title{font-weight:850}.slot-status{display:block;color:#9da9cb;font-size:12px;margin:5px 0}.available{color:#97ffd0}.used{color:#ffc8ef}.empty{color:#ffe58f}.slot form{display:flex;gap:6px;margin-top:9px}.slot input{width:100%;padding:9px;font-size:12px}.slot button{padding:9px;font-size:12px;white-space:nowrap}.history{overflow:auto}table{border-collapse:collapse;width:100%;font-size:12px}th,td{text-align:left;padding:10px;border-bottom:1px solid #2a365d;white-space:nowrap}th{color:#94a3ca}.section{margin:28px 0 12px}.status{font-size:13px}.notice{border:1px solid #745a36;background:#302919;color:#ffdf97;padding:12px;border-radius:12px;margin:12px 0}@media(max-width:560px){.wrap{width:calc(100% - 22px);padding-top:22px}.card,.category{padding:16px}.head{align-items:flex-start}.slots{grid-template-columns:1fr 1fr}.slot form{flex-direction:column}.slot button{width:100%}td,th{padding:8px}}
</style></head><body><main class="wrap"><section id="login" class="card login"><div class="brand">DASHCUP · PRIVATE OPERATIONS</div><h1>Admin sign in</h1><p class="muted">Reward inventory and delivery controls. This portal is separate from the player site.</p><form id="login-form"><label class="field">Username<input id="username" name="username" autocomplete="username" required maxlength="128"></label><label class="field">Password<input id="password" name="password" type="password" autocomplete="current-password" required maxlength="1024"></label><button id="login-button" type="submit">Sign in</button><p id="login-message" class="error" role="status"></p></form></section>
<section id="dashboard" class="hidden"><header class="head"><div><div class="brand">DASHCUP · PRIVATE OPERATIONS</div><h1>Reward inventory</h1></div><button class="secondary" id="logout">Sign out</button></header><div id="config" class="card status"></div><div id="message" class="error" role="status"></div><div id="inventory" class="categories"></div><h2 class="section">Redemption &amp; delivery history</h2><div class="card history"><table><thead><tr><th>Redemption</th><th>Recipient</th><th>Reward</th><th>Slot</th><th>Delivery</th><th>Created</th><th>Resend ID</th><th>Action</th></tr></thead><tbody id="history"></tbody></table></div></section></main>
<script nonce="__CSP_NONCE__">
(()=>{'use strict';const api='https://api.dashcup.com/api/admin';const categories=[['robux','Robux'],['vbucks','V-Bucks'],['freefire','Free Fire Diamonds'],['pubg','PUBG UC'],['cod','COD Points']];const login=document.getElementById('login'),dashboard=document.getElementById('dashboard'),loginForm=document.getElementById('login-form'),loginMessage=document.getElementById('login-message'),message=document.getElementById('message');let busy=false;
async function request(path,options){const response=await fetch(api+path,Object.assign({credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json'}},options||{}));const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Request failed ('+response.status+')');return body}
function setBusy(value){busy=value;document.querySelectorAll('button').forEach(function(button){button.disabled=value})}
function showDashboard(){login.classList.add('hidden');dashboard.classList.remove('hidden')}
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function renderInventory(data){const root=document.getElementById('inventory');root.replaceChildren();categories.forEach(function(category){const items=data.slots.filter(function(slot){return slot.rewardType===category[0]});const counts={available:0,used:0,empty:0,pending:0};items.forEach(function(slot){if(slot.status==='available')counts.available++;else if(slot.status==='used')counts.used++;else if(slot.status==='empty')counts.empty++;else counts.pending++});const section=el('section','category');const title=el('h2','',category[1]);section.append(title,el('p','muted','Available: '+counts.available+' / 20  ·  Used/Sent: '+counts.used+' / 20  ·  Empty: '+counts.empty+' / 20'+(counts.pending?'  ·  Reserved/failed: '+counts.pending:'')));const list=el('div','slots');items.forEach(function(slot){const box=el('article','slot');const state=slot.status==='available'?'AVAILABLE':slot.status==='used'?'USED / SENT · REFILL SLOT':slot.status==='empty'?'EMPTY — REFILL REQUIRED':String(slot.status).toUpperCase().replaceAll('_',' ');const tone=slot.status==='available'?'available':slot.status==='used'?'used':slot.status==='empty'?'empty':'';box.append(el('div','slot-title','Slot '+slot.slotNumber),el('span','slot-status '+tone,state));if(slot.status==='empty'||slot.status==='used'){const form=el('form','');const input=document.createElement('input');input.type='password';input.autocomplete='off';input.maxLength=256;input.required=true;input.placeholder='Paste new code';input.setAttribute('aria-label','New '+category[1]+' code for slot '+slot.slotNumber);const save=el('button','',slot.status==='used'?'Replace':'Save code');save.type='submit';form.append(input,save);form.addEventListener('submit',async function(event){event.preventDefault();if(!input.value)return;setBusy(true);message.textContent='';try{const result=await request('/inventory/'+category[0]+'/'+slot.slotNumber,{method:'POST',body:JSON.stringify({code:input.value})});input.value='';message.textContent=result.duplicate?'That code already exists in inventory.':'Slot saved as AVAILABLE.';message.className='good';await refresh()}catch(error){message.textContent=error.message;message.className='error'}finally{setBusy(false)}});box.append(form)}list.append(box)});section.append(list);root.append(section)})}
function renderHistory(rows){const body=document.getElementById('history');body.replaceChildren();rows.forEach(function(row){const tr=document.createElement('tr');[row.id,row.email,row.rewardType+'',row.slotNumber?String(row.slotNumber):'—',row.deliveryStatus,row.createdAt,row.resendMessageId||'—'].forEach(function(value){const td=document.createElement('td');td.textContent=String(value||'—');tr.append(td)});const action=document.createElement('td');if(row.deliveryStatus==='rejected'){const retry=el('button','secondary','Retry delivery');retry.addEventListener('click',async function(){setBusy(true);message.textContent='';try{await request('/redemptions/'+encodeURIComponent(row.id)+'/retry',{method:'POST',body:'{}'});message.textContent='Retry queued for the same redemption and code.';message.className='good';await refresh()}catch(error){message.textContent=error.message;message.className='error'}finally{setBusy(false)}});action.append(retry)}else if(row.deliveryStatus==='provider_unknown'){const note=el('span','muted','Check Resend before reconciling. ');const messageId=document.createElement('input');messageId.type='text';messageId.autocomplete='off';messageId.maxLength=128;messageId.placeholder='Resend message ID (if sent)';messageId.setAttribute('aria-label','Resend message ID for redemption '+row.id);const sent=el('button','secondary','Confirm sent');const notSent=el('button','danger','Confirm not sent');async function reconcile(resolution){if(!window.confirm(resolution==='sent'?'Confirm that Resend shows this exact redemption was sent?':'Confirm that Resend shows this redemption was not sent?'))return;setBusy(true);message.textContent='';try{await request('/redemptions/'+encodeURIComponent(row.id)+'/reconcile',{method:'POST',body:JSON.stringify({resolution:resolution,...(resolution==='sent'?{messageId:messageId.value.trim()}:{})})});message.textContent=resolution==='sent'?'Delivery recorded as sent.':'Delivery marked rejected; retry will reuse the same code.';message.className='good';await refresh()}catch(error){message.textContent=error.message;message.className='error'}finally{setBusy(false)}}sent.addEventListener('click',function(){void reconcile('sent')});notSent.addEventListener('click',function(){void reconcile('not_sent')});action.append(note,messageId,sent,notSent)}tr.append(action);body.append(tr)})}
async function refresh(){const data=await request('/inventory');const config=document.getElementById('config');config.replaceChildren(el('strong','', 'Delivery configuration: '+(data.delivery.enabledAndConfigured?'READY':'DISABLED / INCOMPLETE')));config.append(el('div','muted','Email flag: '+(data.delivery.enabled?'enabled':'disabled')+' · API key: '+(data.delivery.apiKeyConfigured?'configured':'missing')+' · Sender: '+(data.delivery.senderConfigured?'configured':'missing')+' · Webhook: '+(data.delivery.webhookConfigured?'configured':'missing')+' · Encryption: '+(data.delivery.encryptionConfigured?'configured':'missing')));renderInventory(data);const history=await request('/redemptions');renderHistory(history.redemptions)}
loginForm.addEventListener('submit',async function(event){event.preventDefault();if(busy)return;setBusy(true);loginMessage.textContent='';try{await request('/auth/login',{method:'POST',body:JSON.stringify({username:document.getElementById('username').value,password:document.getElementById('password').value})});document.getElementById('password').value='';showDashboard();await refresh()}catch(error){loginMessage.textContent=error.message;document.getElementById('password').value=''}finally{setBusy(false)}});
document.getElementById('logout').addEventListener('click',async function(){setBusy(true);try{await request('/auth/logout',{method:'POST',body:'{}'})}catch{}finally{dashboard.classList.add('hidden');login.classList.remove('hidden');loginMessage.textContent='Signed out.';setBusy(false)}});
request('/session').then(function(){showDashboard();return refresh()}).catch(function(){});
})();
</script></body></html>`

export function renderAdminPortal(nonce: string) {
  return ADMIN_PORTAL.replaceAll('__CSP_NONCE__', nonce)
}
